google_analytics_id: UA-56996624-1

repository: https://github.com/iROCKBUNNY/qutong

timezone: Asia/Shanghai

title: Tong QU
description: All About Tong QU
keywords: Tong QU, Homepage
url: http://qutong.me

author: iROCKBUNNY
author_url: http://irockbunny.com
organization: TEELAB
organization_url: http://teelab.net

contact: hello[at]qutong[dot]me
github: https://github.com/iROCKBUNNY

image: /img/Avatar.jpg
logo: /img/Avatar-2.jpg

plugins:
- jekyll-seo-tag
- jekyll-sitemap

exclude:
- .gitignore
- .travis.yml
- LICENSE
- README.md
- CNAME
- Gemfile
- Gemfile.lock
- script
- vendor