version:
  jquery: 3.2.1
  jquery_migrate: 3.0.0
  bootstrap: 3.3.7
  font_awesome: 4.7.0

google_analytics_id: UA-56996624-1

repository: https://github.com/iROCKBUNNY/qutong

timezone: Asia/Shanghai

name: Tong QU
author: iROCKBUNNY
author_url: http://irockbunny.com
organization: TEELAB
organization_url: http://teelab.net
description: All About Tong QU
keywords: Tong QU, Homepage
url: http://qutong.me

logo: /img/Avatar-4.png

gems:
- jekyll-seo-tag
- jekyll-sitemap

exclude:
- .gitignore
- .travis.yml
- LICENSE
- README.md
- CNAME
- Gemfile
- Gemfile.lock
- script
- vendor